---
- name: Configure DevOps Servers
  hosts: all
  become: yes
  remote_user: azureuser
  gather_facts: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - docker
    - security
    - app-deploy
    # - monitoring # Will implement later
