name: Auto-add new issues to Backlog

on:
  issues:
    types: [opened]

jobs:
  add_to_backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Backlog column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project: 'https://github.com/users/bananezaromeo/projects/4'
          column: 'Backlog'
          action: 'add'
