name: Auto-add new issues to Backlog

on:
  issues:
    types: [opened]

jobs:
  add_to_backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Backlog column
        uses: alex-page/github-project-automation-plus@v0.9.2
        with:
          project-url: https://github.com/users/bananezaromeo/projects/4
          column-name: Backlog
          github-token: ${{ secrets.GITHUB_TOKEN }}
