name: Move to In Review when PR is opened

on:
  pull_request:
    types: [opened]

jobs:
  move_to_in_review:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue linked to PR to In Review
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project: ' DevOps Pipeline Implementation'
          column: 'In Review'
          action: 'update'
