name: Move to In Review when PR is opened

on:
  pull_request:
    types: [opened]

jobs:
  move_to_in_review:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue linked to PR to In Review
        uses: alex-page/github-project-automation-plus@v0.9.2
        with:
          project-url: https://github.com/users/bananezaromeo/projects/4
          column-name: In Review
          github-token: ${{ secrets.GITHUB_TOKEN }}
