name: Move to Done when PR is merged

on:
  pull_request:
    types: [closed]

jobs:
  move_to_done:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Move issue linked to merged PR to Done
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project: ' DevOps Pipeline Implementation'
          column: 'Done'
          action: 'update'
