name: Move to In Progress when assigned

on:
  issues:
    types: [assigned]

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move assigned issue to In Progress
        uses: alex-page/github-project-automation-plus@v0.9.2
        with:
          project-url: https://github.com/users/bananezaromeo/projects/4
          column-name: In Progress
          github-token: ${{ secrets.GITHUB_TOKEN }}
