name: Move to In Progress when assigned

on:
  issues:
    types: [assigned]

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move assigned issue to In Progress
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project: ' DevOps Pipeline Implementation'
          column: 'In Progress'
          action: 'update'
